name: Main Push Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - closed
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm test -- --watchAll=false --coverage

            - name: Upload Coverage
              uses: actions/upload-artifact@v3
              with:
                name: coverage
                path: coverage/

            - name: Build
              run: npm run build

            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              env:
                AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                SOURCE_DIR: build

            - name: Notify Slack
              uses: 8398a7/action-slack@v3
              with:
                status: ${{ job.status }}
                fields: repo,message,commit,author,action,workflow
                env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
                if: always()